name=Giorno 4
avatar=mugen-runtime/giorno-4/idle_00_0_0.png
imageHeight=240
idle=mugen-runtime/giorno-4/idle_00_0_0.png;mugen-runtime/giorno-4/idle_01_0_1.png;mugen-runtime/giorno-4/idle_02_0_2.png;mugen-runtime/giorno-4/idle_03_0_3.png
punch=mugen-runtime/giorno-4/punch_00_200_22.png;mugen-runtime/giorno-4/punch_01_200_23.png;mugen-runtime/giorno-4/punch_02_200_24.png;mugen-runtime/giorno-4/punch_03_200_25.png;mugen-runtime/giorno-4/punch_04_200_23.png
kick=mugen-runtime/giorno-4/idle_00_0_0.png;mugen-runtime/giorno-4/idle_01_0_1.png;mugen-runtime/giorno-4/idle_02_0_2.png;mugen-runtime/giorno-4/idle_03_0_3.png
guard=mugen-runtime/giorno-4/guard_00_120_0.png;mugen-runtime/giorno-4/guard_01_120_1.png
hit=mugen-runtime/giorno-4/hit_00_200_6.png;mugen-runtime/giorno-4/hit_01_200_7.png;mugen-runtime/giorno-4/hit_02_200_8.png;mugen-runtime/giorno-4/hit_03_200_8.png
