name=Enrico Pucci
avatar=mugen/pucci/idle_00_420_0.png
color=#f8fafc
accent=#a3e635
speed=1.08
power=1.16
defense=1.08
imageHeight=250
idle=mugen/pucci/idle_00_420_0.png;mugen/pucci/idle_01_420_1.png;mugen/pucci/idle_02_420_2.png;mugen/pucci/idle_03_420_3.png;mugen/pucci/idle_04_420_4.png;mugen/pucci/idle_05_420_5.png
punch=mugen/pucci/punch_00_8805_128.png;mugen/pucci/punch_01_8805_129.png;mugen/pucci/punch_02_8805_131.png;mugen/pucci/punch_03_8805_132.png
kick=mugen/pucci/kick_00_1051_1.png;mugen/pucci/kick_01_1051_2.png;mugen/pucci/kick_02_1051_3.png;mugen/pucci/kick_03_1051_4.png;mugen/pucci/kick_04_1051_5.png
guard=mugen/pucci/guard_00_120_1.png
hit=mugen/pucci/hit_00_8805_99.png;mugen/pucci/hit_01_8805_100.png
