name=Joseph
avatar=mugen-runtime/joseph/idle_00_0_5.png
imageHeight=240
idle=mugen-runtime/joseph/idle_00_0_5.png;mugen-runtime/joseph/idle_01_0_6.png;mugen-runtime/joseph/idle_02_0_7.png;mugen-runtime/joseph/idle_03_0_8.png
punch=mugen-runtime/joseph/punch_00_200_39.png;mugen-runtime/joseph/punch_01_200_40.png;mugen-runtime/joseph/punch_02_200_41.png;mugen-runtime/joseph/punch_03_200_42.png;mugen-runtime/joseph/punch_04_200_42.png;mugen-runtime/joseph/punch_05_200_43.png;mugen-runtime/joseph/punch_06_200_38.png
kick=mugen-runtime/joseph/idle_00_0_5.png;mugen-runtime/joseph/idle_01_0_6.png;mugen-runtime/joseph/idle_02_0_7.png;mugen-runtime/joseph/idle_03_0_8.png
guard=mugen-runtime/joseph/guard_00_0_70.png;mugen-runtime/joseph/guard_01_0_71.png
hit=mugen-runtime/joseph/hit_00_200_8.png;mugen-runtime/joseph/hit_01_200_9.png;mugen-runtime/joseph/hit_02_200_0.png;mugen-runtime/joseph/hit_03_200_1.png
