name=boxingDio
avatar=mugen-runtime/boxingdio/idle_00_7_17.png
imageHeight=240
idle=mugen-runtime/boxingdio/idle_00_7_17.png;mugen-runtime/boxingdio/idle_01_7_18.png;mugen-runtime/boxingdio/idle_02_7_19.png;mugen-runtime/boxingdio/idle_03_7_20.png
punch=mugen-runtime/boxingdio/punch_00_7_0.png;mugen-runtime/boxingdio/punch_01_7_5.png;mugen-runtime/boxingdio/punch_02_7_3.png;mugen-runtime/boxingdio/punch_03_7_6.png;mugen-runtime/boxingdio/punch_04_7_7.png
kick=mugen-runtime/boxingdio/idle_00_7_17.png;mugen-runtime/boxingdio/idle_01_7_18.png;mugen-runtime/boxingdio/idle_02_7_19.png;mugen-runtime/boxingdio/idle_03_7_20.png
guard=mugen-runtime/boxingdio/guard_00_7_4.png
hit=mugen-runtime/boxingdio/hit_00_7_0.png;mugen-runtime/boxingdio/hit_01_7_7.png;mugen-runtime/boxingdio/hit_02_7_7.png;mugen-runtime/boxingdio/hit_03_7_8.png;mugen-runtime/boxingdio/hit_04_7_7.png
