name=Hol Horse
avatar=mugen-runtime/hol-horse/idle_00_0_0.png
imageHeight=240
idle=mugen-runtime/hol-horse/idle_00_0_0.png;mugen-runtime/hol-horse/idle_01_0_1.png;mugen-runtime/hol-horse/idle_02_0_2.png
punch=mugen-runtime/hol-horse/punch_00_200_0.png;mugen-runtime/hol-horse/punch_01_200_1.png;mugen-runtime/hol-horse/punch_02_200_2.png;mugen-runtime/hol-horse/punch_03_200_3.png;mugen-runtime/hol-horse/punch_04_200_5.png
kick=mugen-runtime/hol-horse/kick_00_230_1.png;mugen-runtime/hol-horse/kick_01_230_2.png;mugen-runtime/hol-horse/kick_02_230_3.png;mugen-runtime/hol-horse/kick_03_230_4.png;mugen-runtime/hol-horse/kick_04_230_5.png;mugen-runtime/hol-horse/kick_05_230_6.png;mugen-runtime/hol-horse/kick_06_230_7.png;mugen-runtime/hol-horse/kick_07_230_8.png;mugen-runtime/hol-horse/kick_08_230_9.png;mugen-runtime/hol-horse/kick_09_230_10.png
guard=mugen-runtime/hol-horse/guard_00_120_1.png
hit=mugen-runtime/hol-horse/hit_00_0_2.png;mugen-runtime/hol-horse/hit_01_200_58.png;mugen-runtime/hol-horse/hit_02_200_53.png;mugen-runtime/hol-horse/hit_03_190_16.png
