name=Shigechi
avatar=mugen-runtime/shigechi/idle_00_2_0.png
imageHeight=240
idle=mugen-runtime/shigechi/idle_00_2_0.png;mugen-runtime/shigechi/idle_01_2_1.png
punch=mugen-runtime/shigechi/punch_00_200_0.png;mugen-runtime/shigechi/punch_01_200_1.png;mugen-runtime/shigechi/punch_02_200_2.png
kick=mugen-runtime/shigechi/idle_00_2_0.png;mugen-runtime/shigechi/idle_01_2_1.png
guard=mugen-runtime/shigechi/guard_00_5_0.png
hit=mugen-runtime/shigechi/hit_00_500_0.png
