name=Jolynev2
avatar=mugen-runtime/jolynev2/idle_00_0_1.png
imageHeight=240
idle=mugen-runtime/jolynev2/idle_00_0_1.png;mugen-runtime/jolynev2/idle_01_0_0.png;mugen-runtime/jolynev2/idle_02_0_2.png;mugen-runtime/jolynev2/idle_03_0_3.png;mugen-runtime/jolynev2/idle_04_0_4.png
punch=mugen-runtime/jolynev2/punch_00_200_0.png;mugen-runtime/jolynev2/punch_01_200_1.png;mugen-runtime/jolynev2/punch_02_200_2.png;mugen-runtime/jolynev2/punch_03_200_3.png
kick=mugen-runtime/jolynev2/kick_00_230_1.png;mugen-runtime/jolynev2/kick_01_230_2.png;mugen-runtime/jolynev2/kick_02_230_3.png;mugen-runtime/jolynev2/kick_03_230_4.png;mugen-runtime/jolynev2/kick_04_230_5.png;mugen-runtime/jolynev2/kick_05_230_6.png;mugen-runtime/jolynev2/kick_06_230_7.png;mugen-runtime/jolynev2/kick_07_230_8.png;mugen-runtime/jolynev2/kick_08_230_9.png;mugen-runtime/jolynev2/kick_09_230_10.png
guard=mugen-runtime/jolynev2/guard_00_120_1.png
hit=mugen-runtime/jolynev2/hit_00_200_33.png;mugen-runtime/jolynev2/hit_01_200_34.png;mugen-runtime/jolynev2/hit_02_200_35.png
