name=Hermes
avatar=mugen-runtime/hermes/idle_00_2_0.png
imageHeight=240
idle=mugen-runtime/hermes/idle_00_2_0.png;mugen-runtime/hermes/idle_01_2_1.png;mugen-runtime/hermes/idle_02_2_2.png;mugen-runtime/hermes/idle_03_2_1.png
punch=mugen-runtime/hermes/punch_00_200_0.png;mugen-runtime/hermes/punch_01_200_1.png;mugen-runtime/hermes/punch_02_200_2.png
kick=mugen-runtime/hermes/idle_00_2_0.png;mugen-runtime/hermes/idle_01_2_1.png;mugen-runtime/hermes/idle_02_2_2.png;mugen-runtime/hermes/idle_03_2_1.png
guard=mugen-runtime/hermes/guard_00_5_0.png
hit=mugen-runtime/hermes/hit_00_500_0.png
