name=SakuyaIzayoi 1
avatar=mugen-runtime/sakuyaizayoi-1/idle_00_0_3.png
imageHeight=240
idle=mugen-runtime/sakuyaizayoi-1/idle_00_0_3.png;mugen-runtime/sakuyaizayoi-1/idle_01_0_4.png;mugen-runtime/sakuyaizayoi-1/idle_02_0_5.png;mugen-runtime/sakuyaizayoi-1/idle_03_0_6.png;mugen-runtime/sakuyaizayoi-1/idle_04_0_7.png;mugen-runtime/sakuyaizayoi-1/idle_05_0_8.png
punch=mugen-runtime/sakuyaizayoi-1/punch_00_200_0.png;mugen-runtime/sakuyaizayoi-1/punch_01_200_1.png;mugen-runtime/sakuyaizayoi-1/punch_02_200_2.png;mugen-runtime/sakuyaizayoi-1/punch_03_200_2.png
kick=mugen-runtime/sakuyaizayoi-1/idle_00_0_3.png;mugen-runtime/sakuyaizayoi-1/idle_01_0_4.png;mugen-runtime/sakuyaizayoi-1/idle_02_0_5.png;mugen-runtime/sakuyaizayoi-1/idle_03_0_6.png;mugen-runtime/sakuyaizayoi-1/idle_04_0_7.png;mugen-runtime/sakuyaizayoi-1/idle_05_0_8.png
guard=mugen-runtime/sakuyaizayoi-1/guard_00_120_0.png
hit=mugen-runtime/sakuyaizayoi-1/hit_00_5001_0.png
