name=Polnareff 1
avatar=mugen-runtime/polnareff-1/idle_00_1_0.png
imageHeight=240
idle=mugen-runtime/polnareff-1/idle_00_1_0.png;mugen-runtime/polnareff-1/idle_01_1_1.png;mugen-runtime/polnareff-1/idle_02_1_2.png;mugen-runtime/polnareff-1/idle_03_1_3.png
punch=mugen-runtime/polnareff-1/punch_00_200_0.png;mugen-runtime/polnareff-1/punch_01_200_1.png;mugen-runtime/polnareff-1/punch_02_200_2.png;mugen-runtime/polnareff-1/punch_03_200_2.png;mugen-runtime/polnareff-1/punch_04_200_3.png
kick=mugen-runtime/polnareff-1/kick_00_230_0.png;mugen-runtime/polnareff-1/kick_01_230_1.png;mugen-runtime/polnareff-1/kick_02_230_2.png;mugen-runtime/polnareff-1/kick_03_230_3.png;mugen-runtime/polnareff-1/kick_04_230_4.png;mugen-runtime/polnareff-1/kick_05_230_4.png;mugen-runtime/polnareff-1/kick_06_230_5.png
guard=mugen-runtime/polnareff-1/guard_00_120_0.png
hit=mugen-runtime/polnareff-1/hit_00_5000_0.png
