name=Akira
avatar=mugen-runtime/akira/idle_00_2_0.png
imageHeight=240
idle=mugen-runtime/akira/idle_00_2_0.png;mugen-runtime/akira/idle_01_2_1.png;mugen-runtime/akira/idle_02_2_2.png;mugen-runtime/akira/idle_03_2_3.png;mugen-runtime/akira/idle_04_2_0.png;mugen-runtime/akira/idle_05_2_1.png;mugen-runtime/akira/idle_06_2_4.png;mugen-runtime/akira/idle_07_2_3.png
punch=mugen-runtime/akira/punch_00_200_0.png;mugen-runtime/akira/punch_01_200_1.png;mugen-runtime/akira/punch_02_200_2.png
kick=mugen-runtime/akira/idle_00_2_0.png;mugen-runtime/akira/idle_01_2_1.png;mugen-runtime/akira/idle_02_2_2.png;mugen-runtime/akira/idle_03_2_3.png;mugen-runtime/akira/idle_04_2_0.png;mugen-runtime/akira/idle_05_2_1.png;mugen-runtime/akira/idle_06_2_4.png;mugen-runtime/akira/idle_07_2_3.png
guard=mugen-runtime/akira/guard_00_180_0.png
hit=mugen-runtime/akira/hit_00_180_0.png
