name=Stroheim
avatar=mugen-runtime/stroheim/idle_00_0_0.png
imageHeight=240
idle=mugen-runtime/stroheim/idle_00_0_0.png;mugen-runtime/stroheim/idle_01_0_1.png
punch=mugen-runtime/stroheim/punch_00_0_0.png;mugen-runtime/stroheim/punch_01_200_0.png;mugen-runtime/stroheim/punch_02_200_1.png;mugen-runtime/stroheim/punch_03_200_2.png;mugen-runtime/stroheim/punch_04_200_3.png
kick=mugen-runtime/stroheim/kick_00_230_1.png;mugen-runtime/stroheim/kick_01_230_2.png;mugen-runtime/stroheim/kick_02_230_3.png;mugen-runtime/stroheim/kick_03_230_4.png;mugen-runtime/stroheim/kick_04_230_5.png;mugen-runtime/stroheim/kick_05_230_6.png;mugen-runtime/stroheim/kick_06_230_7.png;mugen-runtime/stroheim/kick_07_230_8.png;mugen-runtime/stroheim/kick_08_230_9.png;mugen-runtime/stroheim/kick_09_230_10.png
guard=mugen-runtime/stroheim/guard_00_120_1.png
hit=mugen-runtime/stroheim/hit_00_190_0.png;mugen-runtime/stroheim/hit_01_190_1.png;mugen-runtime/stroheim/hit_02_190_2.png
