name=PolnareffPart5
avatar=mugen-runtime/polnareffpart5/idle_00_1_0.png
imageHeight=240
idle=mugen-runtime/polnareffpart5/idle_00_1_0.png;mugen-runtime/polnareffpart5/idle_01_1_1.png
punch=mugen-runtime/polnareffpart5/idle_00_1_0.png;mugen-runtime/polnareffpart5/idle_01_1_1.png
kick=mugen-runtime/polnareffpart5/idle_00_1_0.png;mugen-runtime/polnareffpart5/idle_01_1_1.png
guard=mugen-runtime/polnareffpart5/guard_00_5_0.png
hit=mugen-runtime/polnareffpart5/hit_00_50_0.png
