name=Kakyoin
avatar=mugen-runtime/kakyoin/idle_00_0_0.png
imageHeight=240
idle=mugen-runtime/kakyoin/idle_00_0_0.png
punch=mugen-runtime/kakyoin/punch_00_8805_46.png;mugen-runtime/kakyoin/punch_01_8805_47.png;mugen-runtime/kakyoin/punch_02_8805_48.png;mugen-runtime/kakyoin/punch_03_8805_48.png;mugen-runtime/kakyoin/punch_04_8805_49.png;mugen-runtime/kakyoin/punch_05_8805_49.png
kick=mugen-runtime/kakyoin/kick_00_1051_1.png;mugen-runtime/kakyoin/kick_01_1051_2.png;mugen-runtime/kakyoin/kick_02_1051_3.png;mugen-runtime/kakyoin/kick_03_1051_4.png;mugen-runtime/kakyoin/kick_04_1051_5.png;mugen-runtime/kakyoin/kick_05_1051_6.png;mugen-runtime/kakyoin/kick_06_1051_7.png;mugen-runtime/kakyoin/kick_07_1051_8.png;mugen-runtime/kakyoin/kick_08_1051_9.png;mugen-runtime/kakyoin/kick_09_1051_10.png
guard=mugen-runtime/kakyoin/guard_00_120_1.png
hit=mugen-runtime/kakyoin/hit_00_8805_43.png;mugen-runtime/kakyoin/hit_01_8805_44.png;mugen-runtime/kakyoin/hit_02_8805_45.png;mugen-runtime/kakyoin/hit_03_8805_46.png
