name=Dio
avatar=mugen-runtime/dio/idle_00_0_7.png
imageHeight=240
idle=mugen-runtime/dio/idle_00_0_7.png;mugen-runtime/dio/idle_01_0_8.png;mugen-runtime/dio/idle_02_0_9.png;mugen-runtime/dio/idle_03_0_10.png
punch=mugen-runtime/dio/punch_00_200_35.png;mugen-runtime/dio/punch_01_200_36.png;mugen-runtime/dio/punch_02_200_37.png;mugen-runtime/dio/punch_03_200_39.png;mugen-runtime/dio/punch_04_200_40.png;mugen-runtime/dio/punch_05_200_40.png;mugen-runtime/dio/punch_06_200_34.png
kick=mugen-runtime/dio/kick_00_200_58.png;mugen-runtime/dio/kick_01_200_59.png;mugen-runtime/dio/kick_02_200_60.png;mugen-runtime/dio/kick_03_200_61.png;mugen-runtime/dio/kick_04_200_62.png
guard=mugen-runtime/dio/guard_00_120_0.png
hit=mugen-runtime/dio/hit_00_6000_0.png
