name=Star Platinum
avatar=mugen-runtime/star-platinum/idle_00_1_0.png
imageHeight=240
idle=mugen-runtime/star-platinum/idle_00_1_0.png;mugen-runtime/star-platinum/idle_01_1_1.png;mugen-runtime/star-platinum/idle_02_1_4.png;mugen-runtime/star-platinum/idle_03_1_3.png
punch=mugen-runtime/star-platinum/punch_00_1_0.png;mugen-runtime/star-platinum/punch_01_1_31.png;mugen-runtime/star-platinum/punch_02_1_32.png
kick=mugen-runtime/star-platinum/idle_00_1_0.png;mugen-runtime/star-platinum/idle_01_1_1.png;mugen-runtime/star-platinum/idle_02_1_4.png;mugen-runtime/star-platinum/idle_03_1_3.png
guard=mugen-runtime/star-platinum/guard_00_1_0.png
hit=mugen-runtime/star-platinum/hit_00_1_0.png;mugen-runtime/star-platinum/hit_01_1_0.png;mugen-runtime/star-platinum/hit_02_1_26.png;mugen-runtime/star-platinum/hit_03_1_27.png;mugen-runtime/star-platinum/hit_04_1_26.png;mugen-runtime/star-platinum/hit_05_1_27.png
