name=Vander
avatar=sheet|cc0/vander-sheet.png|0|0|24|24|true
color=#38bdf8
accent=#facc15
speed=1.18
power=0.92
defense=0.94
imageHeight=174
idle=sheet|cc0/vander-sheet.png|0|0|24|24|true;sheet|cc0/vander-sheet.png|24|0|24|24|true;sheet|cc0/vander-sheet.png|48|0|24|24|true
punch=sheet|cc0/vander-sheet.png|0|192|24|24|true;sheet|cc0/vander-sheet.png|24|192|24|24|true;sheet|cc0/vander-sheet.png|48|192|24|24|true
kick=sheet|cc0/vander-sheet.png|0|240|24|24|true;sheet|cc0/vander-sheet.png|24|240|24|24|true;sheet|cc0/vander-sheet.png|48|240|24|24|true
guard=sheet|cc0/vander-sheet.png|0|96|24|24|true
hit=sheet|cc0/vander-sheet.png|96|192|24|24|true;sheet|cc0/vander-sheet.png|120|192|24|24|true
