name=Mista
avatar=mugen-runtime/mista/idle_00_0_1.png
imageHeight=240
idle=mugen-runtime/mista/idle_00_0_1.png;mugen-runtime/mista/idle_01_0_0.png
punch=mugen-runtime/mista/punch_00_200_13.png;mugen-runtime/mista/punch_01_200_14.png;mugen-runtime/mista/punch_02_200_15.png;mugen-runtime/mista/punch_03_200_13.png
kick=mugen-runtime/mista/kick_00_200_32.png;mugen-runtime/mista/kick_01_200_33.png;mugen-runtime/mista/kick_02_200_34.png
guard=mugen-runtime/mista/guard_00_3_2.png
hit=mugen-runtime/mista/hit_00_4_0.png
