name=Secco
avatar=mugen-runtime/secco/idle_00_1_0.png
imageHeight=240
idle=mugen-runtime/secco/idle_00_1_0.png;mugen-runtime/secco/idle_01_1_1.png
punch=mugen-runtime/secco/punch_00_1_0.png;mugen-runtime/secco/punch_01_10_0.png;mugen-runtime/secco/punch_02_10_1.png
kick=mugen-runtime/secco/idle_00_1_0.png;mugen-runtime/secco/idle_01_1_1.png
guard=mugen-runtime/secco/guard_00_7_0.png
hit=mugen-runtime/secco/hit_00_1_0.png;mugen-runtime/secco/hit_01_4_0.png;mugen-runtime/secco/hit_02_4_1.png;mugen-runtime/secco/hit_03_4_2.png;mugen-runtime/secco/hit_04_1_1.png
