name=High DIO
avatar=mugen-runtime/high-dio/idle_00_0_11.png
imageHeight=240
idle=mugen-runtime/high-dio/idle_00_0_11.png;mugen-runtime/high-dio/idle_01_0_12.png;mugen-runtime/high-dio/idle_02_0_13.png;mugen-runtime/high-dio/idle_03_0_14.png
punch=mugen-runtime/high-dio/punch_00_200_35.png;mugen-runtime/high-dio/punch_01_200_36.png;mugen-runtime/high-dio/punch_02_200_37.png;mugen-runtime/high-dio/punch_03_200_39.png;mugen-runtime/high-dio/punch_04_200_40.png;mugen-runtime/high-dio/punch_05_200_40.png;mugen-runtime/high-dio/punch_06_200_34.png
kick=mugen-runtime/high-dio/kick_00_200_58.png;mugen-runtime/high-dio/kick_01_200_59.png;mugen-runtime/high-dio/kick_02_200_60.png;mugen-runtime/high-dio/kick_03_200_61.png;mugen-runtime/high-dio/kick_04_200_62.png
guard=mugen-runtime/high-dio/guard_00_120_1.png;mugen-runtime/high-dio/guard_01_120_0.png
hit=mugen-runtime/high-dio/hit_00_200_6.png;mugen-runtime/high-dio/hit_01_200_7.png;mugen-runtime/high-dio/hit_02_200_8.png;mugen-runtime/high-dio/hit_03_200_8.png
