name=JosukeGappy
avatar=mugen-runtime/josukegappy/idle_00_0_0.png
imageHeight=240
idle=mugen-runtime/josukegappy/idle_00_0_0.png;mugen-runtime/josukegappy/idle_01_2_1.png;mugen-runtime/josukegappy/idle_02_2_2.png;mugen-runtime/josukegappy/idle_03_2_1.png
punch=mugen-runtime/josukegappy/punch_00_200_0.png;mugen-runtime/josukegappy/punch_01_200_1.png;mugen-runtime/josukegappy/punch_02_200_2.png
kick=mugen-runtime/josukegappy/kick_00_200_5.png;mugen-runtime/josukegappy/kick_01_200_6.png;mugen-runtime/josukegappy/kick_02_200_7.png
guard=mugen-runtime/josukegappy/guard_00_5_0.png
hit=mugen-runtime/josukegappy/hit_00_500_0.png;mugen-runtime/josukegappy/hit_01_500_2.png
