name=Prosciutto
avatar=mugen-runtime/prosciutto/idle_00_0_0.png
imageHeight=240
idle=mugen-runtime/prosciutto/idle_00_0_0.png;mugen-runtime/prosciutto/idle_01_0_1.png;mugen-runtime/prosciutto/idle_02_0_2.png;mugen-runtime/prosciutto/idle_03_0_1.png
punch=mugen-runtime/prosciutto/punch_00_200_3.png;mugen-runtime/prosciutto/punch_01_200_4.png;mugen-runtime/prosciutto/punch_02_200_5.png
kick=mugen-runtime/prosciutto/idle_00_0_0.png;mugen-runtime/prosciutto/idle_01_0_1.png;mugen-runtime/prosciutto/idle_02_0_2.png;mugen-runtime/prosciutto/idle_03_0_1.png
guard=mugen-runtime/prosciutto/guard_00_120_1.png
hit=mugen-runtime/prosciutto/hit_00_41_0.png;mugen-runtime/prosciutto/hit_01_701_1.png
