name=Diego
avatar=mugen-runtime/diego/idle_00_0_0.png
imageHeight=240
idle=mugen-runtime/diego/idle_00_0_0.png;mugen-runtime/diego/idle_01_0_1.png;mugen-runtime/diego/idle_02_0_2.png;mugen-runtime/diego/idle_03_0_3.png;mugen-runtime/diego/idle_04_0_2.png
punch=mugen-runtime/diego/punch_00_200_15.png;mugen-runtime/diego/punch_01_200_16.png;mugen-runtime/diego/punch_02_200_17.png;mugen-runtime/diego/punch_03_200_17.png;mugen-runtime/diego/punch_04_200_18.png
kick=mugen-runtime/diego/kick_00_200_10.png;mugen-runtime/diego/kick_01_200_11.png;mugen-runtime/diego/kick_02_200_12.png;mugen-runtime/diego/kick_03_200_13.png;mugen-runtime/diego/kick_04_200_13.png;mugen-runtime/diego/kick_05_200_12.png;mugen-runtime/diego/kick_06_200_14.png;mugen-runtime/diego/kick_07_200_8.png
guard=mugen-runtime/diego/guard_00_120_0.png
hit=mugen-runtime/diego/hit_00_5_0.png;mugen-runtime/diego/hit_01_5_1.png;mugen-runtime/diego/hit_02_5_2.png;mugen-runtime/diego/hit_03_5_3.png;mugen-runtime/diego/hit_04_5_4.png;mugen-runtime/diego/hit_05_5_5.png;mugen-runtime/diego/hit_06_5_6.png
