name=Risotto
avatar=mugen-runtime/risotto/idle_00_2_0.png
imageHeight=240
idle=mugen-runtime/risotto/idle_00_2_0.png;mugen-runtime/risotto/idle_01_2_1.png;mugen-runtime/risotto/idle_02_2_2.png;mugen-runtime/risotto/idle_03_2_3.png;mugen-runtime/risotto/idle_04_2_4.png;mugen-runtime/risotto/idle_05_2_5.png
punch=mugen-runtime/risotto/punch_00_200_0.png;mugen-runtime/risotto/punch_01_200_1.png;mugen-runtime/risotto/punch_02_200_2.png
kick=mugen-runtime/risotto/kick_00_200_10.png;mugen-runtime/risotto/kick_01_200_11.png;mugen-runtime/risotto/kick_02_200_12.png;mugen-runtime/risotto/kick_03_200_13.png
guard=mugen-runtime/risotto/guard_00_5_0.png
hit=mugen-runtime/risotto/hit_00_180_0.png
