name=Jotaro
avatar=mugen/jotaro/idle_00_0_0.png
color=#14b8a6
accent=#f59e0b
speed=1.33
power=1.28
defense=1.00
imageHeight=240
idle=mugen/jotaro/idle_00_0_0.png;mugen/jotaro/idle_01_0_1.png;mugen/jotaro/idle_02_0_2.png;mugen/jotaro/idle_03_0_3.png;mugen/jotaro/idle_04_0_4.png;mugen/jotaro/idle_05_0_5.png
punch=mugen/jotaro/punch_00_200_0.png;mugen/jotaro/punch_01_200_1.png;mugen/jotaro/punch_02_200_2.png;mugen/jotaro/punch_03_200_2.png;mugen/jotaro/punch_04_200_3.png
kick=mugen/jotaro/special_00_200_31.png;mugen/jotaro/special_01_200_32.png;mugen/jotaro/special_02_200_33.png;mugen/jotaro/special_03_200_34.png
guard=mugen/jotaro/guard_00_120_1.png
hit=mugen/jotaro/hit_00_0_8.png;mugen/jotaro/hit_01_0_9.png;mugen/jotaro/hit_02_0_10.png;mugen/jotaro/hit_03_0_11.png
