name=Dio
avatar=mugen/dio/idle_00_0_7.png
color=#22c55e
accent=#fde047
speed=1.10
power=0.99
defense=0.99
imageHeight=240
idle=mugen/dio/idle_00_0_7.png;mugen/dio/idle_01_0_8.png;mugen/dio/idle_02_0_9.png;mugen/dio/idle_03_0_10.png
punch=mugen/dio/punch_00_200_35.png;mugen/dio/punch_01_200_36.png;mugen/dio/punch_02_200_37.png;mugen/dio/punch_03_200_39.png;mugen/dio/punch_04_200_40.png
kick=mugen/dio/kick_00_200_58.png;mugen/dio/kick_01_200_59.png;mugen/dio/kick_02_200_60.png;mugen/dio/kick_03_200_61.png;mugen/dio/kick_04_200_62.png
guard=mugen/dio/guard_00_120_0.png
hit=mugen/dio/hit_00_6000_0.png
