name=Sakuya
avatar=mugen-runtime/sakuya/idle_00_0_0.png
imageHeight=240
idle=mugen-runtime/sakuya/idle_00_0_0.png;mugen-runtime/sakuya/idle_01_0_1.png;mugen-runtime/sakuya/idle_02_0_2.png;mugen-runtime/sakuya/idle_03_0_1.png
punch=mugen-runtime/sakuya/punch_00_200_0.png;mugen-runtime/sakuya/punch_01_200_1.png;mugen-runtime/sakuya/punch_02_200_2.png;mugen-runtime/sakuya/punch_03_200_2.png;mugen-runtime/sakuya/punch_04_230_1.png
kick=mugen-runtime/sakuya/idle_00_0_0.png;mugen-runtime/sakuya/idle_01_0_1.png;mugen-runtime/sakuya/idle_02_0_2.png;mugen-runtime/sakuya/idle_03_0_1.png
guard=mugen-runtime/sakuya/guard_00_120_0.png
hit=mugen-runtime/sakuya/hit_00_195_0.png;mugen-runtime/sakuya/hit_01_195_1.png;mugen-runtime/sakuya/hit_02_195_2.png;mugen-runtime/sakuya/hit_03_195_3.png
