name=Jean Pierre Polnareff
avatar=mugen/polnareff/idle_00_0_0.png
color=#60a5fa
accent=#e5e7eb
speed=1.22
power=1.08
defense=0.94
imageHeight=245
idle=mugen/polnareff/idle_00_0_0.png;mugen/polnareff/idle_01_0_1.png;mugen/polnareff/idle_02_0_2.png;mugen/polnareff/idle_03_0_1.png
punch=mugen/polnareff/punch_00_200_0.png;mugen/polnareff/punch_01_200_1.png;mugen/polnareff/punch_02_200_2.png;mugen/polnareff/punch_03_200_3.png
kick=mugen/polnareff/kick_00_230_1.png;mugen/polnareff/kick_01_230_2.png;mugen/polnareff/kick_02_230_3.png;mugen/polnareff/kick_03_230_4.png;mugen/polnareff/kick_04_230_5.png
guard=mugen/polnareff/idle_02_0_2.png
hit=mugen/polnareff/hit_00_0_0.png;mugen/polnareff/hit_01_0_3.png;mugen/polnareff/hit_02_0_4.png
