name=Jonathan
avatar=mugen-runtime/jonathan/idle_00_0_1.png
imageHeight=240
idle=mugen-runtime/jonathan/idle_00_0_1.png;mugen-runtime/jonathan/idle_01_0_2.png;mugen-runtime/jonathan/idle_02_0_3.png;mugen-runtime/jonathan/idle_03_0_0.png
punch=mugen-runtime/jonathan/punch_00_200_8.png;mugen-runtime/jonathan/punch_01_200_1.png;mugen-runtime/jonathan/punch_02_200_2.png;mugen-runtime/jonathan/punch_03_200_3.png;mugen-runtime/jonathan/punch_04_200_4.png;mugen-runtime/jonathan/punch_05_200_5.png;mugen-runtime/jonathan/punch_06_200_8.png
kick=mugen-runtime/jonathan/idle_00_0_1.png;mugen-runtime/jonathan/idle_01_0_2.png;mugen-runtime/jonathan/idle_02_0_3.png;mugen-runtime/jonathan/idle_03_0_0.png
guard=mugen-runtime/jonathan/guard_00_0_70.png;mugen-runtime/jonathan/guard_01_0_71.png
hit=mugen-runtime/jonathan/hit_00_200_8.png;mugen-runtime/jonathan/hit_01_200_9.png;mugen-runtime/jonathan/hit_02_200_0.png
