name=LisaLisa
avatar=mugen-runtime/lisalisa/idle_00_0_0.png
imageHeight=240
idle=mugen-runtime/lisalisa/idle_00_0_0.png;mugen-runtime/lisalisa/idle_01_0_1.png;mugen-runtime/lisalisa/idle_02_0_2.png;mugen-runtime/lisalisa/idle_03_0_3.png
punch=mugen-runtime/lisalisa/punch_00_200_0.png;mugen-runtime/lisalisa/punch_01_200_1.png;mugen-runtime/lisalisa/punch_02_200_2.png;mugen-runtime/lisalisa/punch_03_200_3.png;mugen-runtime/lisalisa/punch_04_200_1.png
kick=mugen-runtime/lisalisa/idle_00_0_0.png;mugen-runtime/lisalisa/idle_01_0_1.png;mugen-runtime/lisalisa/idle_02_0_2.png;mugen-runtime/lisalisa/idle_03_0_3.png
guard=mugen-runtime/lisalisa/guard_00_120_0.png
hit=mugen-runtime/lisalisa/hit_00_6000_0.png
