name=Josuke 3
avatar=mugen-runtime/josuke-3/idle_00_0_0.png
imageHeight=240
idle=mugen-runtime/josuke-3/idle_00_0_0.png;mugen-runtime/josuke-3/idle_01_0_1.png;mugen-runtime/josuke-3/idle_02_0_2.png;mugen-runtime/josuke-3/idle_03_0_3.png
punch=mugen-runtime/josuke-3/punch_00_200_30.png;mugen-runtime/josuke-3/punch_01_200_27.png;mugen-runtime/josuke-3/punch_02_200_28.png;mugen-runtime/josuke-3/punch_03_200_29.png;mugen-runtime/josuke-3/punch_04_200_29.png;mugen-runtime/josuke-3/punch_05_200_30.png
kick=mugen-runtime/josuke-3/idle_00_0_0.png;mugen-runtime/josuke-3/idle_01_0_1.png;mugen-runtime/josuke-3/idle_02_0_2.png;mugen-runtime/josuke-3/idle_03_0_3.png
guard=mugen-runtime/josuke-3/guard_00_0_70.png;mugen-runtime/josuke-3/guard_01_0_71.png
hit=mugen-runtime/josuke-3/hit_00_200_0.png;mugen-runtime/josuke-3/hit_01_200_1.png;mugen-runtime/josuke-3/hit_02_200_2.png;mugen-runtime/josuke-3/hit_03_200_3.png;mugen-runtime/josuke-3/hit_04_200_4.png
