name=Trish Una
avatar=mugen-runtime/trish-una/idle_00_0_0.png
imageHeight=240
idle=mugen-runtime/trish-una/idle_00_0_0.png;mugen-runtime/trish-una/idle_01_0_1.png;mugen-runtime/trish-una/idle_02_0_2.png;mugen-runtime/trish-una/idle_03_0_1.png;mugen-runtime/trish-una/idle_04_0_0.png
punch=mugen-runtime/trish-una/punch_00_200_0.png;mugen-runtime/trish-una/punch_01_200_1.png;mugen-runtime/trish-una/punch_02_200_2.png
kick=mugen-runtime/trish-una/kick_00_203_0.png;mugen-runtime/trish-una/kick_01_203_1.png;mugen-runtime/trish-una/kick_02_203_2.png;mugen-runtime/trish-una/kick_03_203_3.png;mugen-runtime/trish-una/kick_04_203_4.png
guard=mugen-runtime/trish-una/guard_00_120_1.png
hit=mugen-runtime/trish-una/hit_00_1000_5.png
