name=Avdol
avatar=mugen-runtime/avdol/idle_00_0_0.png
imageHeight=240
idle=mugen-runtime/avdol/idle_00_0_0.png;mugen-runtime/avdol/idle_01_0_1.png;mugen-runtime/avdol/idle_02_0_2.png;mugen-runtime/avdol/idle_03_0_1.png
punch=mugen-runtime/avdol/punch_00_200_0.png;mugen-runtime/avdol/punch_01_200_1.png;mugen-runtime/avdol/punch_02_200_2.png;mugen-runtime/avdol/punch_03_200_3.png;mugen-runtime/avdol/punch_04_210_0.png
kick=mugen-runtime/avdol/kick_00_230_0.png;mugen-runtime/avdol/kick_01_230_1.png;mugen-runtime/avdol/kick_02_230_2.png;mugen-runtime/avdol/kick_03_230_3.png;mugen-runtime/avdol/kick_04_230_3.png;mugen-runtime/avdol/kick_05_230_4.png
guard=mugen-runtime/avdol/guard_00_120_0.png
hit=mugen-runtime/avdol/hit_00_5000_0.png
