name=Narancia
avatar=mugen-runtime/narancia/idle_00_0_0.png
imageHeight=240
idle=mugen-runtime/narancia/idle_00_0_0.png;mugen-runtime/narancia/idle_01_0_1.png
punch=mugen-runtime/narancia/punch_00_5_0.png;mugen-runtime/narancia/punch_01_5_1.png;mugen-runtime/narancia/punch_02_5_2.png;mugen-runtime/narancia/punch_03_5_3.png;mugen-runtime/narancia/punch_04_5_3.png
kick=mugen-runtime/narancia/idle_00_0_0.png;mugen-runtime/narancia/idle_01_0_1.png
guard=mugen-runtime/narancia/guard_00_6_0.png
hit=mugen-runtime/narancia/hit_00_9_4.png;mugen-runtime/narancia/hit_01_9_5.png
