name=Vanilla Ice
avatar=mugen-runtime/vanilla-ice/idle_00_0_0.png
imageHeight=240
idle=mugen-runtime/vanilla-ice/idle_00_0_0.png;mugen-runtime/vanilla-ice/idle_01_0_1.png;mugen-runtime/vanilla-ice/idle_02_0_2.png;mugen-runtime/vanilla-ice/idle_03_0_5.png
punch=mugen-runtime/vanilla-ice/punch_00_200_0.png;mugen-runtime/vanilla-ice/punch_01_200_1.png;mugen-runtime/vanilla-ice/punch_02_200_2.png
kick=mugen-runtime/vanilla-ice/idle_00_0_0.png;mugen-runtime/vanilla-ice/idle_01_0_1.png;mugen-runtime/vanilla-ice/idle_02_0_2.png;mugen-runtime/vanilla-ice/idle_03_0_5.png
guard=mugen-runtime/vanilla-ice/guard_00_120_1.png
hit=mugen-runtime/vanilla-ice/hit_00_5000_0.png;mugen-runtime/vanilla-ice/hit_01_5000_10.png
