name=Melone
avatar=mugen-runtime/melone/idle_00_2_0.png
imageHeight=240
idle=mugen-runtime/melone/idle_00_2_0.png;mugen-runtime/melone/idle_01_2_1.png;mugen-runtime/melone/idle_02_2_2.png;mugen-runtime/melone/idle_03_2_1.png
punch=mugen-runtime/melone/punch_00_200_0.png;mugen-runtime/melone/punch_01_200_1.png;mugen-runtime/melone/punch_02_200_2.png;mugen-runtime/melone/punch_03_200_0.png
kick=mugen-runtime/melone/idle_00_2_0.png;mugen-runtime/melone/idle_01_2_1.png;mugen-runtime/melone/idle_02_2_2.png;mugen-runtime/melone/idle_03_2_1.png
guard=mugen-runtime/melone/guard_00_2_0.png
hit=mugen-runtime/melone/hit_00_500_0.png
