name=Shadow Dio
avatar=mugen-runtime/shadow-dio/idle_00_0_0.png
imageHeight=240
idle=mugen-runtime/shadow-dio/idle_00_0_0.png;mugen-runtime/shadow-dio/idle_01_0_1.png;mugen-runtime/shadow-dio/idle_02_0_2.png;mugen-runtime/shadow-dio/idle_03_0_3.png
punch=mugen-runtime/shadow-dio/punch_00_200_31.png;mugen-runtime/shadow-dio/punch_01_200_32.png;mugen-runtime/shadow-dio/punch_02_200_33.png;mugen-runtime/shadow-dio/punch_03_200_34.png
kick=mugen-runtime/shadow-dio/kick_00_200_58.png;mugen-runtime/shadow-dio/kick_01_200_59.png;mugen-runtime/shadow-dio/kick_02_200_60.png;mugen-runtime/shadow-dio/kick_03_200_61.png;mugen-runtime/shadow-dio/kick_04_200_62.png
guard=mugen-runtime/shadow-dio/guard_00_120_0.png;mugen-runtime/shadow-dio/guard_01_120_0.png
hit=mugen-runtime/shadow-dio/hit_00_200_8.png;mugen-runtime/shadow-dio/hit_01_200_7.png
